# -*- coding: utf-8 -*-
"""numpy and scipy.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vYUNpML0fHgeNu_zq1VeWp7ZbH8xygZD
"""

from scipy.optimize import *

def f(x):
    return (x - 3) ** 2

res = minimize(f, 2)

res

def func(v):
    x, y, z = v
    return (x + 1)/(y + 1) + (y - 1)/(z + 2) + (z - 3)/(x + 4)

import numpy as np
res = minimize(func, (1, 1, 1))

res

x = np.linspace(0, 2000, 10)

from matplotlib import pyplot as plt

plt.scatter(x, x ** 2)

from scipy.interpolate import interp1d

f = interp1d(x, x ** 2, kind='quadratic')

x = np.linspace(0, 2000, 100)
plt.plot(x, f(x))

from scipy.optimize import curve_fit

def f(x):
    return (x - 3) ** 2